### ISSUE TITLE
Migrating `conftest.py` from parent test dirs includes ALL unit tests

### ISSUE THREAD

**Issue by mkrizek** [ansible/collection_migration#90]
When https://github.com/ansible/collection_migration/pull/88 is run on the following spec:
```yaml
modules:
  - packaging/os/yum.py
```

It correctly includes `conftest.py`'s from parent dirs:
```
'test/units/modules/conftest.py': 'tests/unit/modules/packaging/os/conftest.py',
'test/units/modules/packaging/os/conftest.py': 'tests/unit/modules/packaging/os/conftest.py',
```

However, in process of doing so it also includes ALL module unit tests with them. I believe this is because of the following code adding `conftest.py`'s into `matching_test_modules`:
https://github.com/ansible/collection_migration/blob/b18c4a2e3b7fc08f4285ab0b4bad50e40238a919/migrate.py#L699-L703

which is then processed to find related test files:
https://github.com/ansible/collection_migration/blob/b18c4a2e3b7fc08f4285ab0b4bad50e40238a919/migrate.py#L803-L813

The problem is that in case of `test/units/modules/conftest.py` (not limited to) it means that it goes through `test/units/modules` and adds all modules unit tests.

**Comment by webknjaz** [comment]
@mkrizek please check if this https://github.com/ansible/collection_migration/pull/97 fixes the problem.

**Comment by webknjaz** [comment]
@bcoca PR #97 is awaiting merge
